### ISSUE TITLE
Implement null data type

### ISSUE THREAD

**Issue by juusaw** [jantuomi/tunkki#11]
It is a widely accepted convention to have a data type that represents the lack of data.  Typically this is called `null` (`nil` or `undefined` in some languages). _tunkki_ could really use a structure like this. For the reserved word I would find `nada` a good choice.

**Comment by onnilampi** [comment]
For the sake of clarity I would suggest that there exist an alternative for `nada`. My personal recommendation is `JonSnowknowsthis`
