### ISSUE TITLE
Runtime in C

### ISSUE THREAD

**Issue by juusaw** [jantuomi/tunkki#2]
Is it possible to implement the runtime also in C? My use case is in embedded systems and I can't use JVM on the device.

**Comment by onnilampi** [comment]
This really is a hot topic with hardware manufacturers! I'm personally waiting for this like a CFGO in a new startup.

**Comment by jantuomi** [comment]
Please refer to [the java website](https://docs.oracle.com/javase/8/embedded/develop-apps-platforms/overview.htm) for information about getting java running in your environment. Closing as not relevant.
